name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"
  pull_request:
    branches:
      - 'main'

env:
  CACHE_IMAGE: ghcr.io/firms-gta/testpublishingdockerimages-cache
  DOCKER_BUILDKIT: 1
  RENV_PATHS_ROOT: /root/.cache/R/renv

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Calculate the hash of renv.lock
      - name: Calculate renv.lock hash
        id: renv_lock
        run: echo "renv_lock_hash=$(sha256sum renv.lock | cut -d' ' -f1)" >> $GITHUB_ENV
      
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ env.renv_lock_hash }}
          restore-keys: |
            ${{ runner.os }}-renv-

      # Calculate the hash of DOI.csv
      - name: Calculate DOI.csv hash
        id: doi_csv
        run: echo "doi_csv_hash=$(sha256sum data/DOI2.csv | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/firms-gta/testpublishingdockerimages
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.url=${{ github.repository }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.title=Testshinyappdeployement
            org.opencontainers.image.description=Shinyapptest for deployment
            org.opencontainers.image.vendor=IRD
            org.opencontainers.image.author=Bastien Grasset <bastien.grasset@ird.fr>

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master,network=host

      - name: Cache Docker layers for R packages
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache/packages
          key: ${{ runner.os }}-buildx-packages-${{ env.renv_lock_hash }}
          restore-keys: |
            ${{ runner.os }}-buildx-packages-

      - name: Cache Docker layers for data download
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache/data
          key: ${{ runner.os }}-buildx-data-${{ env.doi_csv_hash }}
          restore-keys: |
            ${{ runner.os }}-buildx-data-
        
      - name: Build Docker image
        run: |
          docker buildx build \
            --no-cache \
            --progress=plain \
            --tag ghcr.io/firms-gta/testpublishingdockerimages:latest \
            --output type=docker,dest=/tmp/docker-image.tar \
            .

      - name: Load Docker image
        if: github.ref_type == 'tag'
        run: |
          docker load -i /tmp/docker-image.tar

      - name: Conditional push Docker image
        if: github.ref_type == 'tag'
        run: |
          TAG_NAME=$(basename ${GITHUB_REF})
          docker tag ghcr.io/firms-gta/testpublishingdockerimages:latest ghcr.io/firms-gta/testpublishingdockerimages:${TAG_NAME}
          docker push ghcr.io/firms-gta/testpublishingdockerimages:latest
          docker push ghcr.io/firms-gta/testpublishingdockerimages:${TAG_NAME}
